In [1]:
import numpy as np

# Basics

## Initializing

In [2]:
array1 = np.array([1,2,3])
print("array1 type:", type(array1))
print("array1 shape:", array1.shape)

array1 type: <class 'numpy.ndarray'>
array1 shape: (3,)


In [4]:
array2 = np.array([[1,2,3], [2,3,4]])
print("array2 type:", type(array2))
print("array2 shape:", array2.shape)

array2 type: <class 'numpy.ndarray'>
array2 shape: (2, 3)


In [5]:
array3 = np.array([[1,2,3]])
print("array3 type:", type(array3))
print("array3 shape:", array3.shape)

array3 type: <class 'numpy.ndarray'>
array3 shape: (1, 3)


In [9]:
print("array2 is {} dimension".format(array2.ndim))
print("array2 data type:", array2.dtype)

array2 is 2 dimension
array2 data type: int32


In [19]:
sequence_array = np.arange(10)
print(sequence_array, sequence_array.shape)
sequence_array = np.arange(1,11)
print(sequence_array, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9] (10,)
[ 1  2  3  4  5  6  7  8  9 10] (10,)


In [21]:
zero = np.zeros((3,2), dtype="int32") #default is float64
print(zero, zero.dtype, zero.shape)
ones = np.ones((2,2))
print(ones, ones.dtype, ones.shape)

[[0 0]
 [0 0]
 [0 0]] int32 (3, 2)
[[1. 1.]
 [1. 1.]] float64 (2, 2)


## Converting data type

In [17]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

[1. 2. 3.] float64


## Reshaping

In [23]:
array1 = np.arange(10)
print("array1:\n", array1)
array2 = array1.reshape(2,5)
print("array2:\n", array2)

#if -1 is passed, automatically calculate the shape
array2 = array1.reshape(-1, 5)
print("array2:\n", array2)


array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
